name: Build test and push
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: get thumbor version
        id: thumbor
        run: |
          set -eo pipefail
          LINE=$(grep -Ei '^thumbor(\[[^]]+\])?==[0-9][^#[:space:]]*' thumbor/requirements.txt | head -n1 || true)
          if [ -n "$LINE" ]; then
            VERSION=$(echo "$LINE" | sed -E 's/.*==([^#[:space:]]+).*/\1/')
          else
            echo "No explicit thumbor== version found in requirements; defaulting to latest" >&2
            VERSION=latest
          fi
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
      - name: build images and load them for testing
        run: |
          ./build
      - name: install bats
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      - name: run bats tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            docker image ls -a
            for filename in tests/*.bats; do sudo bats --tap "$filename" || exit 1; done
      - name: login to ghcr.io
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: minimalcompact
          password: ${{ secrets.GH_TOKEN }}
      - name: push when master
        if: github.ref == 'refs/heads/master'
        run: |
          ./push
